{"name": "测试数据：【 13800138000，111111，True，0，success】", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 0", "trace": "self = <testcases.api_test.test_kuai_login.TestUserLogin object at 0x10318c220>\nphone = '13800138000', verificationCode = '111111', except_result = True\nexcept_code = 0, except_msg = 'success'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {phone}，{verificationCode}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"phone, verificationCode, except_result, except_code, except_msg\",\n                             api_kuai_data[\"test_login_user\"])\n    def test_login_user(self, phone, verificationCode, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(phone, verificationCode)\n        print(\"result:\",result)\n        step_1(phone)\n        assert result.success == except_result, result.error\n        assert result.response.status_code == 200\n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json().get(\"code\")))\n>       assert result.response.json().get(\"code\") == except_code\nE       assert 200 == 0\n\ntest_kuai_login.py:35: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "phone", "value": "'13800138000'"}], "start": 1628071641752, "stop": 1628071641752}], "attachments": [{"name": "log", "source": "e04b06a5-13b8-4ea5-97c1-c343333e1f9d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "360a179c-ec37-42c5-b097-13b0d3bf3804-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a7036210-22c1-4f52-9626-a6866803eb86-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "phone", "value": "'13800138000'"}, {"name": "verificationCode", "value": "'111111'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "0"}, {"name": "except_msg", "value": "'success'"}], "start": 1628071641674, "stop": 1628071641753, "uuid": "91e2d699-0661-4516-b81c-b84aa8c7558f", "historyId": "d6233ac4c765a841f06f7de4dfad4f4e", "testCaseId": "4cf2c2f7c5a680a41fe59cb327f3c0a1", "fullName": "testcases.api_test.test_kuai_login.TestUserLogin#test_login_user", "labels": [{"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--登录用户"}, {"name": "feature", "value": "用户登录模块"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_kuai_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "zengxiaohua.local"}, {"name": "thread", "value": "2293-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_kuai_login"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}